#!/usr/bin/env python3
"""Hermetic unit test for the skill-authority manifest generator (scripts/skill_authorities.py).

skill-authorities.json is alert-out's join key, and it is regenerated by hand wherever the qpwb
skill tree happens to be mounted. Run anywhere else -- the default /mnt/skills/user absent, or
QPWB_SKILLS pointed at the wrong directory -- the generator used to exit 0 having written a freshly
dated manifest over zero skills: it replaced the working one, and heartbeat's age check read it as
fresh, so the watch list went to nothing with every signal green. The load-bearing behavior pinned
here is the refusal: no qpwb-* skills found means a nonzero exit, a stderr message naming --skills
and QPWB_SKILLS, and the manifest at --out left byte-for-byte alone. A real (synthetic) tree still
generates, keeps curated edits, and passes heartbeat.py --skill-manifest, so the generator and the
check agree on what a usable manifest is.

Every path is a temp dir; nothing touches the repo's skill-authorities.json.

Run directly: `python scripts/test_skill_authorities.py`.
"""
import contextlib
import io
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import heartbeat  # noqa: E402
import skill_authorities  # noqa: E402

FAILS = []

SKILL_MD = """---
name: qpwb-premises
description: >-
  Premises-liability drafting for Georgia slip-and-fall claims.
---
The owner's duty to invitees is O.C.G.A. § 51-3-1 `[verify]`.
**Robinson v. Kroger Co., 268 Ga. 735 (1997)** sets the summary-judgment standard.
"""


def check(name, cond, detail=""):
    print(("  ok   " if cond else "  FAIL ") + name + (("  -- " + detail) if (detail and not cond) else ""))
    if not cond:
        FAILS.append(name)


def gen(argv, env_skills=None):
    """Run skill_authorities.main(argv) with QPWB_SKILLS set to env_skills (unset if None) for the
    call only. Returns (exit code, stderr text). Callers always name --skills or env_skills, so the
    real /mnt/skills/user default is never read."""
    saved = os.environ.pop("QPWB_SKILLS", None)
    if env_skills is not None:
        os.environ["QPWB_SKILLS"] = env_skills
    err = io.StringIO()
    try:
        with contextlib.redirect_stderr(err), contextlib.redirect_stdout(io.StringIO()):
            code = skill_authorities.main(argv)
    finally:
        os.environ.pop("QPWB_SKILLS", None)
        if saved is not None:
            os.environ["QPWB_SKILLS"] = saved
    return code, err.getvalue()


def tree(root, skills):
    """Write a skill tree: {dir name: SKILL.md text, or None for a dir with no SKILL.md}."""
    for name, text in skills.items():
        os.makedirs(os.path.join(root, name))
        if text is not None:
            with open(os.path.join(root, name, "SKILL.md"), "w", encoding="utf-8") as f:
                f.write(text)
    return root


def heartbeat_code(path, alert_dir):
    """heartbeat.skill_manifest_check() against the manifest at path (real clock), restoring after."""
    saved = (heartbeat.SA_PATH, heartbeat.SA_ALERT_PATH, heartbeat.SA_DAYS)
    heartbeat.SA_PATH = path
    heartbeat.SA_ALERT_PATH = os.path.join(alert_dir, "sm.md")
    heartbeat.SA_DAYS = 90.0
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            return heartbeat.skill_manifest_check()
    finally:
        heartbeat.SA_PATH, heartbeat.SA_ALERT_PATH, heartbeat.SA_DAYS = saved


def main():
    print("skill_authorities manifest guard:")
    with tempfile.TemporaryDirectory() as d:
        out = os.path.join(d, "skill-authorities.json")

        # A real tree generates, and prev's curated block carries over.
        real = tree(os.path.join(d, "real"), {"qpwb-premises": SKILL_MD})
        with open(out, "w", encoding="utf-8") as f:
            json.dump({"curated": {"qpwb-premises": {"areas": ["premises"]}}}, f)
        code, _ = gen(["--skills", real, "--out", out])
        man = json.load(open(out, encoding="utf-8"))
        check("real tree -> exit 0", code == 0, "got %r" % code)
        check("real tree -> skill_count 1", man.get("skill_count") == 1, repr(man.get("skill_count")))
        check("real tree -> statute and case both indexed",
              set(man.get("by_authority") or {}) == {"O.C.G.A. § 51-3-1", "Robinson v. Kroger Co."},
              repr(sorted(man.get("by_authority") or {})))
        check("curated areas survive regeneration",
              man["skills"]["qpwb-premises"]["areas_status"] == "curated")
        # What the generator writes from a real tree, the heartbeat must accept.
        check("generated manifest passes heartbeat --skill-manifest", heartbeat_code(out, d) == 0)

        with open(out, "rb") as f:
            good = f.read()
        listing = sorted(os.listdir(d))

        # The regression: a missing root. Exit nonzero, name the fix, and write nothing -- the
        # working manifest from the run above must survive untouched.
        missing = os.path.join(d, "no-such-tree")
        code, err = gen(["--skills", missing, "--out", out])
        check("missing skills root -> nonzero exit", code not in (0, None), "got %r" % code)
        check("missing root: stderr names --skills and QPWB_SKILLS",
              "--skills" in err and "QPWB_SKILLS" in err and missing in err, err)
        check("missing root: existing manifest left byte-identical", open(out, "rb").read() == good)
        check("missing root: no file created or left behind", sorted(os.listdir(d)) == listing,
              repr(sorted(os.listdir(d))))

        # A root that exists but holds no qpwb-* skills, and one whose qpwb-* dirs carry no
        # SKILL.md or references: both are zero skills, so both refuse.
        other = tree(os.path.join(d, "other"), {"pdf": "---\nname: pdf\n---\n"})
        code, _ = gen(["--skills", other, "--out", out])
        check("root with no qpwb-* skills -> nonzero, manifest untouched",
              code not in (0, None) and open(out, "rb").read() == good, "got %r" % code)
        hollow = tree(os.path.join(d, "hollow"), {"qpwb-core": None})
        code, _ = gen(["--skills", hollow, "--out", out])
        check("qpwb-* dir with no SKILL.md -> nonzero, manifest untouched",
              code not in (0, None) and open(out, "rb").read() == good, "got %r" % code)

        # The env default takes the same path, and the message names the root it actually read.
        fresh = os.path.join(d, "fresh.json")
        code, err = gen(["--out", fresh], env_skills=other)
        check("QPWB_SKILLS at an empty tree -> nonzero, nothing written",
              code not in (0, None) and not os.path.exists(fresh), "got %r" % code)
        check("QPWB_SKILLS refusal names the root it read", other in err, err)

        # The process exit code, not just main()'s return: the refusal is only a refusal if the
        # shell sees it.
        env = {k: v for k, v in os.environ.items() if k != "QPWB_SKILLS"}
        p = subprocess.run([sys.executable, os.path.join(HERE, "skill_authorities.py"),
                            "--skills", missing, "--out", fresh],
                           cwd=d, env=env, capture_output=True, text=True, timeout=60)
        check("CLI with a missing root exits nonzero", p.returncode != 0, "rc %r" % p.returncode)
        check("CLI refusal goes to stderr, nothing written",
              "QPWB_SKILLS" in p.stderr and not os.path.exists(fresh), p.stderr)

    if FAILS:
        print("\nFAILED: %s" % ", ".join(FAILS))
        return 1
    print("\nALL TESTS PASSED (15 checks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
